language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"

addons:
  apt:
    packages:
      - language-pack-nl

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python manage.py test
  - coverage run --source=orders --omit="*/migrations/*" manage.py test

after_success:
  - coveralls
